apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-kavalan-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-kavalan
  template:
    metadata:
      labels:
        app: pod-kavalan
    spec:
      serviceAccountName: pod-kavalan-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["sleep", "3600"]


