apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.simplybyteService.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.simplybyteService.port }}
      targetPort: {{ .Values.simplybyteService.targetPort }}
      nodePort: {{ .Values.simplybyteService.nodePort }}
